stages:
  - test
  - build
  - deploy

recent-artifacts-backend:
  artifacts:
    expire_in: "1 week"
    paths:
      - backend/target/universal/*.zip
  except:
    - tags
  script:
    - "cd backend && sbt dist"
  stage: build

release-artifacts-backend:
  artifacts:
    paths:
      - backend/target/universal/*.zip
  only:
    - master 
  script:
    - "cd backend && sbt dist"
  stage: build

staging-artifacts-backend:
  artifacts:
    paths:
      - backend/target/universal/*.zip
  only:
    - dev
  script:
    - "cd backend && NODE_ENV=staging sbt dist"
  stage: build

tag_checker:
  only:
    - tags
  script:
    - "python tag_checker.py $CI_COMMIT_TAG"
  stage: build

run-tests:
  except:
    - dev@seng302-2019/team-500
    - master@seng302-2019/team-500
  script:
    - "cd backend && sbt test"
  stage: test

staging-run:
  dependencies:
    - staging-artifacts-backend
  script: 
    - "cd backend/target/universal"
    - unzip seng302-team-500-0.0.1-SNAPSHOT.zip
    - pm2 delete dev-server || true
    - sudo rm -rf /var/www/dev/seng302-team-500-0.0.1-SNAPSHOT
    - sudo cp -r seng302-team-500-0.0.1-SNAPSHOT /var/www/dev
    - cd /var/www/dev/seng302-team-500-0.0.1-SNAPSHOT/bin
    - pm2 start "sudo bash seng302-team-500 -Dhttp.port=8443" --name=dev-server
  only:
    - dev
  stage: deploy

production-run:
  dependencies:
    - release-artifacts-backend
  script: 
    - "cd backend/target/universal"
    - unzip seng302-team-500-0.0.1-SNAPSHOT.zip
    - sudo ./opt/startserver -p stop
    - sudo rm -rf /var/www/prod/*
    - sudo cp -r seng302-team-500-0.0.1-SNAPSHOT/ /var/www/prod/
    - cd /var/www/prod/conf
    - sudo mv application.prod.conf application.conf
    - cd /opt
    - sudo ./startserver -p start
  only:
    - master
  stage: deploy



after_script:
  - "sudo chown -R gitlab-runner:gitlab-runner ."

update-sonar:
 stage: test
 script:
    - cd backend && sbt jacoco
    - cd .. && export PATH=$PATH:/opt/sonarqubeScanner/bin
    - sonar-scanner  --debug
 only:
    - master@seng302-2019/team-500
    - dev@seng302-2019/team-500
