tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

run-tests:
  stage: test
  script:
    - cd backend && sbt test

recent-artifacts-frontend:
  stage: build 
  script:
    - echo $USER
    - echo "Checking that npm version exists"
    - npm -v
    - cd frontend && npm install && npm run build
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 week
  except:
    - tags

release-artifacts-frontend:
  stage: build 
  script:
  - echo "Checking that npm version exists"
  - npm -v | echo
  - cd frontend && npm install && npm run build
  artifacts:
    paths:
    - frontend/dist
  only:
  - tags

recent-artifacts-backend:
  stage: build 
  script:
    - cd backend && sbt dist
  artifacts:
    paths:
      - backend/target/universal/*.zip
    expire_in: 1 week
  except:
    - tags

release-artifacts-backend:
 stage: build 
 script:
    - cd backend && sbt dist && 
 artifacts:
    paths:
    - backend/target/universal/*.zip
 only:
    - tags

staging-artifacts-backend:
  stage: build 
 script:
    - cd backend && NODE_ENV=staging sbt dist
 artifacts:
    paths:
    - backend/target/universal/*.zip
 only:
  - ci-testing

staging-run:
  stage: deploy 
  script:
    - ls -A
  dependencies:
    - staging-artifacts-backend



    



update-sonar:
 stage: deploy
 script:
    - sonar-scanner
 only:
    - master@seng302-2019/team-500
