stages:
  - test
  - build
  - deploy

# run-tests:
#   before_script:
#     - "cd backend && sbt clean"
#   script:
#     - "sbt test"
#   stage: test

# recent-artifacts-backend:
#   artifacts:
#     expire_in: "1 week"
#     paths:
#       - backend/target/universal/*.zip
#   except:
#     - tags
#   script:
#     - "cd backend && sbt dist"
#   stage: build

# recent-artifacts-frontend:
#   artifacts:
#     expire_in: "1 week"
#     paths:
#       - frontend/dist
#   except:
#     - tags
#   script:
#     - "echo $USER"
#     - "echo \"Checking that npm version exists\""
#     - "npm -v"
#     - "cd frontend && npm install && npm run build"
#   stage: build

# release-artifacts-backend:
#   artifacts:
#     paths:
#       - backend/target/universal/*.zip
#   only:
#     - tags
#   script:
#     - "cd backend && sbt dist &&"
#   stage: build

# release-artifacts-frontend:
#   artifacts:
#     paths:
#       - frontend/dist
#   only:
#     - tags
#   script:
#     - "echo \"Checking that npm version exists\""
#     - "npm -v | echo"
#     - "cd frontend && npm install && npm run build"
#   stage: build

staging-artifacts-backend:
  artifacts:
    paths:
      - backend/target/universal/*.zip
  only:
    - ci-testing
  script:
    - "cd backend && NODE_ENV=staging sbt dist"
  stage: build

tag_checker:
  only:
    - tags
  script:
    - "python tag_checker.py $CI_COMMIT_TAG"
  stage: build

staging-run:
  dependencies:
    - staging-artifacts-backend
  script: 
    - "cd backend/target/universal"
    - unzip seng302-team-500-0.0.1-SNAPSHOT.zip
    - pm2 delete dev-server || true
    - sudo rm /var/www/dev/seng302-team-500-0.0.1-SNAPSHOT || true 
    - sudo cp -r seng302-team-500-0.0.1-SNAPSHOT /var/www/dev
    - cd /var/www/dev/bin
    - pm2 start "sudo bash seng302-team-500 -Dhttp.port=8443" --name=dev-server
    - pm2 logs
  only:
    - ci-testing
  stage: deploy

after_script:
  - "sudo chown -R gitlab-runner:gitlab-runner ."

update-sonar:
  only:
    - master@seng302-2019/team-500
  script:
    - sonar-scanner
